# PHP as Linux Web App on Azure
# Build, package and deploy your PHP project to Azure Linux Web App.
trigger:
- master

pool:
  name: PrivateAgents

variables:
  azureSubscription: 'e4cd9437-c3d6-437a-ab1f-774ebb120f4b'  # Use your actual service connection
  webAppName: 'mahmoudgklayytech'                            # Use your actual web app name 
  vmImageName: 'PrivateAgents'                               # Use your actual agent pool name         

stages:
- stage: BuildAndDeploy
  displayName: Build and Deploy Stage
  jobs:
  - job: SingleAgentJob
    displayName: Build and Deploy Job
    pool:
      name: $(vmImageName)
    steps:
    - checkout: self

    - task: ArchiveFiles@2
      displayName: 'Archive Application Folder'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/Application'
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
        replaceExistingArchive: true

    - task: AzureWebApp@1
      displayName: 'Deploy to Azure Web App'
      inputs:
        azureSubscription: $(azureSubscription)
        appName: $(webAppName)
        appType: webAppLinux
        package: '$(Build.ArtifactStagingDirectory)/app.zip'
