# trigger:
# - master

pool:
  name: PrivateAgents

variables:
  registryName: 'mahmoudg'
  imageName: 'pizza'
  tags: '$(Build.BuildId)'

steps:
- checkout: self

- task: AzureCLI@2
  displayName: 'Login to ACR'
  inputs:
    azureSubscription: 'MyAzureServiceConnection'   # ARM service connection
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az acr login --name $(registryName)